// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mnf_Portal.Infrastructure.Persistence;

#nullable disable

namespace Mnf_Portal.Infrastructure.Migrations
{
    [DbContext(typeof(MnfDbContext))]
    partial class MnfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mnf_Portal.Core.Entities.NewsGallary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("Gallaries");
                });

            modelBuilder.Entity("Mnf_Portal.Core.Entities.NewsTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Abbr");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Body");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Head");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("Lang_Id");

                    b.Property<int?>("NewsId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Source");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("prtl_News_Translations", (string)null);
                });

            modelBuilder.Entity("Mnf_Portal.Core.Entities.PortalNews", b =>
                {
                    b.Property<int>("News_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("News_Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("News_date");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_img");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Owner_ID");

                    b.HasKey("News_Id");

                    b.ToTable("prtl_News", (string)null);
                });

            modelBuilder.Entity("Mnf_Portal.Core.Entities.NewsGallary", b =>
                {
                    b.HasOne("Mnf_Portal.Core.Entities.PortalNews", "PortalNews")
                        .WithMany("Gallaries")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortalNews");
                });

            modelBuilder.Entity("Mnf_Portal.Core.Entities.NewsTranslation", b =>
                {
                    b.HasOne("Mnf_Portal.Core.Entities.PortalNews", "News")
                        .WithMany("Translations")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("News");
                });

            modelBuilder.Entity("Mnf_Portal.Core.Entities.PortalNews", b =>
                {
                    b.Navigation("Gallaries");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
